apiVersion: v1

kind: Service

metadata:
  name: gitea-setup-service
  namespace: gitea-service
spec:
  type: ClusterIP

  ports:
    - port: 80
      targetPort: 3000

  selector:
      server: gitea-deployment

