---
# Source: gitea/templates/namespace.yaml
apiVersion: v1
kind: Namespace

metadata:
  name: gitea-ns
  labels:
    name: gitea-ns
---
# Source: gitea/templates/config.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: gitea
  labels:
    app: gitea
data:
  Name:  gitea
  Env: Dev
---
# Source: gitea/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gitea-service
  namespace: gitea-ns
spec:
  type:  NodePort
  ports:
    - port:  80
      targetPort:  3000
      nodePort:  30000
  selector:
    server: gitea
---
# Source: gitea/templates/deployment.yaml
apiVersion : apps/v1
kind: Deployment

metadata:
  name: gitea-deployment
  namespace: gitea-ns
spec:
  replicas: 3

  selector:
    matchLabels:
      server: gitea

  template:
    metadata:
      labels:
        server: gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production