gitea:
  name: gitea
  replicas: 3

  deployment:
    name: gitea-deployment

  image:
    name: gitea/gitea
    port: 3000
  
  service:
    name: gitea-service
    type: NodePort
    port: 80
    targetPort: 3000
    nodePort: 30000

  namespace:
    name: gitea-ns

  env : Dev

serviceAccount:
  create: false
  annotations: {}
  name: "gitea"