apiVersion : apps/v1
kind: Deployment

metadata:
  name: gitea
  namespace: default
spec:
  replicas: 3

  selector:
    matchLabels:
      server: gitea

  template:
    metadata:
      labels:
        server: gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production