apiVersion: v1
kind: Service
metadata:
  name: gitea-servie
  namespace: gitea-ns
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000
  selector:
    server: {{ .Values.gitea.name }}

  # Optional
  # type: LoadBalancer
  # ports:
  #   - port: 80
  #     targetPort: 3000