apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000
  selector:
    server: gitea

  # Optional
  # type: LoadBalancer
  # ports:
  #   - port: 80
  #     targetPort: 3000