apiVersion: v1
kind: Service
metadata:
  name: {{.Values.gitea.service.name}}
  namespace: {{ .Values.gitea.namespace.name }}
spec:
  type:  {{ .Values.gitea.service.type }}
  ports:
    - port:  {{ .Values.gitea.service.port }}
      targetPort:  {{ .Values.gitea.service.targetPort }}
      nodePort:  {{ .Values.gitea.service.nodePort }}
  selector:
    server: {{ .Values.gitea.name }}